import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Jumbotron from '../components/Pages/Landing/Jumbotron';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Inclusify</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Jumbotron />
            </main>
        </div>
    );
}
